runtime: nodejs16
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0

handlers:
  - url: /static
    static_dir: static
  - url: /(.*\.(json|ico|js))$
    static_files: \1
    upload: .*\.(json|ico|js)$
  - url: .*
    static_files: index.html
    upload: index.html
  